---
title: "Untitled"
output: pdf_document
---


```{r, echo=FALSE}
library(Quandl)
library(TTR)
# enter auth code
Quandl.auth("mW11caB1btTqNnBWGhtg")

GetStock <- function(mkt,ma){
  atr <- ATR(mkt[c(3,4,5)], n = 14)
  mkt <- cbind(mkt, atr[,c(1,2)])
  mkt$atr <- round(mkt$atr)
  mkt$MA <- round(runMean(mkt$Close,n=ma))
  mkt$diff <- round(mkt$Close - mkt$MA)
  mkt$OC <- round(mkt$Close - mkt$Open)
  mkt$Tog <- ifelse(mkt$diff>0,mkt$Low-mkt$MA,mkt$MA-mkt$High)
  return(mkt)
}
```

```{r, echo=FALSE}


# for(i in 1:length(file.names)){
#   file <- read.table(file.names[i], header=F, sep=",", stringsAsFactors=FALSE)
#   file <- file[,c(1,2,3,4,5)]
#   colnames(file) <- c('Date','Open','High','Low','Close')
#   file <- GetStock(file,10)
#   print(file.names[i])
#   print(tail(file))
#   print("")
# }

```

```{r, echo=FALSE}

df10 <- as.data.frame(matrix(seq(11),nrow=1,ncol=5))


setwd("D:/VM Share/aaStocks")
path = 'D:/VM Share/aaStocks'
file.names <- dir(path, pattern =".csv")

GetStock2 <- function(mkt,ma){
  atr <- ATR(mkt[c(3,4,5)], n = 14)
  mkt <- cbind(mkt, atr[,c(1,2)])
  mkt$atr <- round(mkt$atr)
  mkt$MA <- round(runMean(mkt$Close,n=ma))
  mkt$diff <- round(mkt$Close - mkt$MA)
  mkt$OC <- round(mkt$Close - mkt$Open)
  mkt$Tog <- ifelse(mkt$diff>0,mkt$Low-mkt$MA,mkt$MA-mkt$High)
  return(mkt)
}

check_long <- function(){
  for(i in 1:length(file.names)){
    full_file <- paste(path, '/', file.names[i], sep="")
    file <- read.table(full_file, header=F, sep=",", stringsAsFactors=FALSE)
    
    file <- file[,c(1,2,3,4,5)]
    colnames(file) <- c('Date','Open','High','Low','Close')
    file <- GetStock2(file,10)
    
    ln <- nrow(file)
    l1 <- file[ln,9]
    l2 <- file[ln-1,9]
    l3 <- file[ln-2,9]
    
    if(l1 > l2 & l2 > l3){
      res <- c(file.names[i], file[ln,5], l1, l2, l3 )
      df10 <- rbind(df10,res)
    }
  }
  colnames(df10) <- c('Stock','Price','L1','L2','L3')
  df10 <- df10[- 1,]
  return(df10)
}

check_short <- function(){
  for(i in 1:length(file.names)){
    full_file <- paste(path, '/', file.names[i], sep="")
    file <- read.table(full_file, header=F, sep=",", stringsAsFactors=FALSE)
    
    file <- file[,c(1,2,3,4,5)]
    colnames(file) <- c('Date','Open','High','Low','Close')
    file <- GetStock2(file,10)
    
    ln <- nrow(file)
    l1 <- file[ln,9]
    l2 <- file[ln-1,9]
    l3 <- file[ln-2,9]
    
    if(l1 < l2 & l2 < l3){
      res <- c(file.names[i], file[ln,5], l1, l2, l3 )
      df10 <- rbind(df10,res)
    }
  }
  colnames(df10) <- c('Stock','Price','L1','L2','L3')
  df10 <- df10[- 1,]
  return(df10)
}

```

## Check Long
```{r, echo=FALSE}
rr <- check_long()
print(rr)
```

## Check Short
```{r, echo=FALSE}
check_short()
```


