---
title: "Untitled"
output: pdf_document
---


```{r, echo=FALSE}
library(Quandl)
library(TTR)
# enter auth code
Quandl.auth("mW11caB1btTqNnBWGhtg")

GetStock <- function(mkt,ma){
  atr <- ATR(mkt[c(3,4,5)], n = 14)
  mkt <- cbind(mkt, atr[,c(1,2)])
  mkt$atr <- round(mkt$atr)
  mkt$MA <- round(runMean(mkt$Close,n=ma))
  mkt$diff <- round(mkt$Close - mkt$MA)
  mkt$OC <- round(mkt$Close - mkt$Open)
  mkt$Tog <- ifelse(mkt$diff>0,mkt$Low-mkt$MA,mkt$MA-mkt$High)
  return(mkt)
}
```

```{r, echo=FALSE}
path = 'D:/VM Share/aaStocks'
file.names <- dir(path, pattern =".csv")

diff <- 100

for(i in 1:length(file.names)){
  full_file <- paste(path, '/', file.names[i], sep="")
  file <- read.table(full_file, header=F, sep=",", stringsAsFactors=FALSE)
  file <- file[,c(1,2,3,4,5)]
  colnames(file) <- c('Date','Open','High','Low','Close')
  ln <- nrow(file)
  ln2 <- ln - diff
  file2 <- file[1:ln2,]
  file2 <- GetStock(file2,10)
  print(file.names[i])
  print(tail(file2,n=10))
  print("")
  print(file[(ln-(diff-1)),])
  print("")
}

```

